# Generated by Django 2.2.3 on 2020-01-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dependants', models.IntegerField(default=0)),
                ('applicantincome', models.IntegerField(default=0)),
                ('coapplicantincome', models.IntegerField(default=0)),
                ('loanamt', models.IntegerField(default=0)),
                ('credithistory', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('graduatededucation', models.CharField(choices=[('graduated', 'graduated'), ('not_graduated', 'not_graduated')], max_length=15)),
                ('selfemployed', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=15)),
                ('area', models.CharField(choices=[('rural', 'rural'), ('semiurban', 'semiurban'), ('urban', 'urban')], max_length=15)),
            ],
        ),
    ]
